package com.mtedd.titreminexcel.enums;

public enum GeneratedDocumentTypeEnum {
    INVOICE, QUOTE, RECEIPT, ACKNOWLEDGEMENT, CERTIFICATE, NOTIFICATION,
    CONVOCATION, DECISION, AGREEMENT, PERMIT, CONTRACT, SUMMARY_REPORT,
    LEGAL_NOTICE, FORMAL_REQUEST, REMINDER, REJECTION, REPORT, TRANSCRIPT,
    DELIVERY_NOTE, OTHER
}