apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: titreminexcel
spec:
  project: default
  source:
    repoURL: 'https://github.com/younesen/titreminexcel.git'
    path: helm-charts/titreminexcel
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
