apiVersion: apps/v1
kind: Deployment
metadata:
  name: titreminexcel-backend
  labels:
    app: titreminexcel-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: titreminexcel-backend
  template:
    metadata:
      labels:
        app: titreminexcel-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

