apiVersion: apps/v1
kind: Deployment
metadata:
  name: titreminexcel-frontend
  labels:
    app: titreminexcel-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: titreminexcel-frontend
  template:
    metadata:
      labels:
        app: titreminexcel-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: REACT_APP_API_URL
              value: "http://titreminexcel-backend:{{ .Values.backend.port }}"

