replicaCount: 1

backend:
  image: younesen/titreminexcel-backend:local
  port: 9091

frontend:
  image: younesen/titreminexcel-frontend:local
  port: 80

service:
  type: NodePort
  frontendNodePort: 31337
  backendNodePort: 31338

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: titreminexcel.local
      paths:
        - path: /
          pathType: Prefix

httpRoute:
  enabled: false
